// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjCJoGRsNV_fridcQGEp2oIwhffcNyJcQ',
    appId: '1:358457203017:web:be5976bfaa58a44966e298',
    messagingSenderId: '358457203017',
    projectId: 'smartpotplant',
    authDomain: 'smartpotplant.firebaseapp.com',
    databaseURL: 'https://smartpotplant-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smartpotplant.firebasestorage.app',
    measurementId: 'G-WGRH774VKJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdO9d7neebkdQobnDtYOsLZymfX0uCMXg',
    appId: '1:358457203017:android:532b66735598fb8966e298',
    messagingSenderId: '358457203017',
    projectId: 'smartpotplant',
    databaseURL: 'https://smartpotplant-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smartpotplant.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhRkwMO8Njt-30dqWxq0NCEHw6PmYGULc',
    appId: '1:358457203017:ios:3c2230f68bf20fb566e298',
    messagingSenderId: '358457203017',
    projectId: 'smartpotplant',
    databaseURL: 'https://smartpotplant-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smartpotplant.firebasestorage.app',
    iosBundleId: 'com.example.smartPlantMonitoring',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhRkwMO8Njt-30dqWxq0NCEHw6PmYGULc',
    appId: '1:358457203017:ios:3c2230f68bf20fb566e298',
    messagingSenderId: '358457203017',
    projectId: 'smartpotplant',
    databaseURL: 'https://smartpotplant-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smartpotplant.firebasestorage.app',
    iosBundleId: 'com.example.smartPlantMonitoring',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjCJoGRsNV_fridcQGEp2oIwhffcNyJcQ',
    appId: '1:358457203017:web:94958769fb23edb566e298',
    messagingSenderId: '358457203017',
    projectId: 'smartpotplant',
    authDomain: 'smartpotplant.firebaseapp.com',
    databaseURL: 'https://smartpotplant-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smartpotplant.firebasestorage.app',
    measurementId: 'G-10LWFEKFXL',
  );
}
